defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: Default

title: Jianxiu Li

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Education & Internship
    link: /education-internship
    icon: ""

  - text: Publications & Patents
    link: /publications-patent
    icon: ""

  - text: Awards
    link: /award
    icon: ""
    
