defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Jianxiu Li
subtitle: Research Assistant

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Brief Bio
    link: /brief-bio
    icon: ""

  - text: Publications
    link: /publications
    icon: ""

  - text: CV
    link: /cv
    icon: ""
    
