defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Jianxiu Li
subtitle: Research Assistant

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Brief Bio
    link: /skills-and-offers
    icon: ""

  - text: Publications
    link: /contact
    icon: ""

  - text: CV
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
