defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: Default

title: Jianxiu Li
subtitle: Research Assistant
description: USC Viterbi School of Engineering

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Education & Internship
    link: /education-internship
    icon: ""

  - text: Publications
    link: /publications
    icon: ""

  - text: Award
    link: /award
    icon: ""
    
